name: 'description-validator-action'
description:
  'GitHub Action to validate pull request descriptions against regex patterns,
  ensuring they comply with your repository templates.'
author: 'Developaul'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github_token:
    description: 'GitHub Token'
    required: true

  pull_request_pattern:
    description: 'Pull request pattern to validate against'
    required: true
runs:
  using: node20
  main: dist/index.js
